// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlljmqzjnrrdqqkwfyvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sbGptcXpqbnJyZHFxa3dmeXZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNjg2NTMsImV4cCI6MjA2NTk0NDY1M30.PgabutFfZTII4RPESbanwyNdFZubniqp25duBwHNWvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);